"use client"

import { useState } from "react"
import { toast } from "sonner"
import { Member, Team, Project, Role, Permission, ActivityLog } from "@/types/organization"

export function useOrganizationData() {
  const [members, setMembers] = useState<Member[]>([
    {
      id: 1,
      name: "Alex Johnson",
      email: "alex@example.com",
      role: "OWNER",
      joinedAt: "2023-05-15",
      status: "active",
      lastActive: "2025-04-20",
      avatar: "/avatars/01.png",
      twoFactorEnabled: true,
      teams: [1, 3],
      skills: ["React", "TypeScript", "UI/UX"],
      location: "San Francisco, CA",
      department: "Engineering",
      bio: "Full-stack developer with 8+ years of experience in building web applications.",
      socialLinks: {
        twitter: "alexj",
        linkedin: "alexjohnson",
        github: "alexj-dev",
      },
    },
    {
      id: 2,
      name: "Maria Garcia",
      email: "maria@example.com",
      role: "ADMIN",
      joinedAt: "2023-06-22",
      status: "active",
      lastActive: "2025-04-19",
      avatar: "/avatars/02.png",
      twoFactorEnabled: false,
      teams: [1, 2, 5],
      skills: ["Product Management", "Agile", "Strategy"],
      location: "New York, NY",
      department: "Product",
      bio: "Product manager focused on user-centered design and data-driven decisions.",
    },
    {
      id: 3,
      name: "John Smith",
      email: "john@example.com",
      role: "MANAGER",
      joinedAt: "2023-07-12",
      status: "active",
      lastActive: "2025-04-18",
      avatar: "/avatars/03.png",
      teams: [2, 4],
      skills: ["Node.js", "MongoDB", "AWS"],
      location: "Austin, TX",
      department: "Engineering",
    },
    {
      id: 4,
      name: "Sarah Kim",
      email: "sarah@example.com",
      role: "MEMBER",
      joinedAt: "2023-08-05",
      status: "inactive",
      lastActive: "2025-03-25",
      avatar: "/avatars/04.png",
      teams: [3],
      skills: ["UI Design", "Figma", "User Research"],
      location: "Seattle, WA",
      department: "Design",
    },
    {
      id: 5,
      name: "David Lee",
      email: "david@example.com",
      role: "MEMBER",
      joinedAt: "2023-09-18",
      status: "active",
      lastActive: "2025-04-21",
      avatar: "/avatars/05.png",
      twoFactorEnabled: true,
      teams: [1, 6],
      skills: ["Python", "Data Analysis", "Machine Learning"],
      location: "Boston, MA",
      department: "Data Science",
    },
  ])

  const [teams, setTeams] = useState<Team[]>([
    {
      id: 1,
      name: "Frontend Team",
      description: "Responsible for UI development",
      members: 8,
      projects: 3,
      progress: 75,
      activity: "high",
      createdAt: "2023-05-20",
      leadId: 1,
      color: "#3b82f6",
      tags: ["React", "Next.js", "UI"],
      completedProjects: 12,
    },
    {
      id: 2,
      name: "Backend Team",
      description: "Handles server-side logic and APIs",
      members: 6,
      projects: 4,
      progress: 60,
      activity: "medium",
      createdAt: "2023-06-15",
      leadId: 2,
      color: "#10b981",
      tags: ["Node.js", "Python", "APIs"],
      completedProjects: 9,
    },
    {
      id: 3,
      name: "Design Team",
      description: "Creates user interfaces and experiences",
      members: 4,
      projects: 5,
      progress: 90,
      activity: "high",
      createdAt: "2023-07-10",
      color: "#8b5cf6",
      tags: ["UI/UX", "Figma", "Design Systems"],
      completedProjects: 15,
    },
    {
      id: 4,
      name: "DevOps Team",
      description: "Manages infrastructure and deployments",
      members: 3,
      projects: 2,
      progress: 45,
      activity: "low",
      createdAt: "2023-08-05",
      color: "#f59e0b",
      tags: ["AWS", "Kubernetes", "CI/CD"],
      completedProjects: 6,
    },
    {
      id: 5,
      name: "QA Team",
      description: "Ensures product quality and testing",
      members: 5,
      projects: 4,
      progress: 80,
      activity: "medium",
      createdAt: "2023-09-12",
      color: "#ec4899",
      tags: ["Testing", "Automation", "QA"],
      completedProjects: 11,
    },
    {
      id: 6,
      name: "Product Team",
      description: "Defines product strategy and roadmap",
      members: 4,
      projects: 3,
      progress: 65,
      activity: "medium",
      createdAt: "2023-10-18",
      leadId: 5,
      color: "#6366f1",
      tags: ["Strategy", "Roadmap", "User Research"],
      completedProjects: 8,
    },
  ])

  const [projects, setProjects] = useState<Project[]>([
    {
      id: 1,
      name: "Website Redesign",
      description: "Redesign the company website with new branding",
      status: "active",
      progress: 85,
      deadline: "2025-05-15",
      startDate: "2025-03-01",
      teamId: 1,
      members: [1, 2, 5],
      priority: "high",
      budget: 25000,
      tags: ["Design", "Frontend", "Branding"],
      milestones: [
        {
          id: 1,
          name: "Design Approval",
          description: "Get stakeholder approval on designs",
          dueDate: "2025-03-15",
          status: "completed",
          projectId: 1,
        },
        {
          id: 2,
          name: "Frontend Implementation",
          description: "Implement approved designs",
          dueDate: "2025-04-30",
          status: "in-progress",
          projectId: 1,
        },
        {
          id: 3,
          name: "Content Migration",
          description: "Migrate content to new site",
          dueDate: "2025-05-10",
          status: "pending",
          projectId: 1,
        },
      ],
    },
    {
      id: 2,
      name: "Mobile App Development",
      description: "Create a new mobile app for customers",
      status: "active",
      progress: 65,
      deadline: "2025-06-20",
      startDate: "2025-02-15",
      teamId: 2,
      members: [2, 3, 6],
      priority: "high",
      budget: 50000,
      tags: ["Mobile", "React Native", "API"],
      milestones: [
        {
          id: 4,
          name: "Requirements Gathering",
          description: "Finalize app requirements",
          dueDate: "2025-03-01",
          status: "completed",
          projectId: 2,
        },
        {
          id: 5,
          name: "UI/UX Design",
          description: "Design app interfaces",
          dueDate: "2025-04-01",
          status: "completed",
          projectId: 2,
        },
        {
          id: 6,
          name: "MVP Development",
          description: "Develop minimum viable product",
          dueDate: "2025-05-15",
          status: "in-progress",
          projectId: 2,
        },
      ],
    },
    {
      id: 3,
      name: "API Overhaul",
      description: "Modernize the API infrastructure",
      status: "active",
      progress: 45,
      deadline: "2025-04-30",
      startDate: "2025-03-10",
      teamId: 2,
      members: [3, 4],
      priority: "medium",
      budget: 30000,
      tags: ["Backend", "API", "Performance"],
      milestones: [
        {
          id: 7,
          name: "API Design",
          description: "Design new API structure",
          dueDate: "2025-03-25",
          status: "completed",
          projectId: 3,
        },
        {
          id: 8,
          name: "Implementation",
          description: "Implement new API endpoints",
          dueDate: "2025-04-15",
          status: "in-progress",
          projectId: 3,
        },
      ],
    },
    {
      id: 4,
      name: "Database Migration",
      description: "Migrate from SQL to NoSQL database",
      status: "on-hold",
      progress: 30,
      deadline: "2025-05-10",
      startDate: "2025-02-20",
      teamId: 4,
      members: [2, 4, 5],
      priority: "medium",
      budget: 20000,
      tags: ["Database", "Migration", "NoSQL"],
    },
    {
      id: 5,
      name: "Marketing Site",
      description: "Build a new marketing landing page",
      status: "completed",
      progress: 100,
      deadline: "2025-04-25",
      startDate: "2025-03-15",
      teamId: 3,
      members: [1, 6],
      priority: "low",
      budget: 15000,
      tags: ["Marketing", "Frontend", "SEO"],
    },
  ])

  const [roles, setRoles] = useState<Role[]>([
    {
      id: "owner",
      name: "Owner",
      description: "Full access to all organization settings and data",
      permissions: ["admin:full"],
      memberCount: 1,
      createdAt: "2023-05-15",
      updatedAt: "2023-05-15",
      createdBy: 1,
    },
    {
      id: "admin",
      name: "Administrator",
      description: "Can manage all aspects except organization ownership",
      permissions: ["user:view", "user:create", "user:edit", "team:create", "team:edit", "project:manage"],
      memberCount: 2,
      createdAt: "2023-05-15",
      updatedAt: "2023-08-20",
      createdBy: 1,
    },
    {
      id: "manager",
      name: "Manager",
      description: "Can manage teams and projects but not organization settings",
      permissions: ["user:view", "team:edit", "project:manage"],
      memberCount: 3,
      createdAt: "2023-05-15",
      updatedAt: "2023-09-10",
      createdBy: 1,
    },
    {
      id: "member",
      name: "Member",
      description: "Standard access with limited permissions",
      permissions: ["user:view"],
      memberCount: 42,
      createdAt: "2023-05-15",
      updatedAt: "2023-05-15",
      createdBy: 1,
    },
  ])

  const [permissions, setPermissions] = useState<Permission[]>([
    {
      id: "user:view",
      name: "View Users",
      description: "Can view organization members",
      category: "Users",
    },
    {
      id: "user:create",
      name: "Create Users",
      description: "Can invite and create new members",
      category: "Users",
    },
    {
      id: "user:edit",
      name: "Edit Users",
      description: "Can modify user profiles and roles",
      category: "Users",
    },
    {
      id: "user:delete",
      name: "Delete Users",
      description: "Can remove users from organization",
      category: "Users",
    },
    {
      id: "team:create",
      name: "Create Teams",
      description: "Can create new teams",
      category: "Teams",
    },
    {
      id: "team:edit",
      name: "Edit Teams",
      description: "Can modify team settings",
      category: "Teams",
    },
    {
      id: "team:delete",
      name: "Delete Teams",
      description: "Can remove teams",
      category: "Teams",
    },
    {
      id: "project:create",
      name: "Create Projects",
      description: "Can create new projects",
      category: "Projects",
    },
    {
      id: "project:edit",
      name: "Edit Projects",
      description: "Can modify project settings",
      category: "Projects",
    },
    {
      id: "project:delete",
      name: "Delete Projects",
      description: "Can remove projects",
      category: "Projects",
    },
    {
      id: "admin:full",
      name: "Admin Access",
      description: "Full administrative access",
      category: "Organization",
    },
  ])

  const [activityLogs, setActivityLogs] = useState<ActivityLog[]>([
    {
      id: 1,
      user: "Alex Johnson",
      userId: 1,
      action: "invited",
      target: "Michael Brown",
      targetId: 7,
      targetType: "user",
      timestamp: "2025-04-21T09:15:32Z",
      ipAddress: "192.168.1.1",
    },
    {
      id: 2,
      user: "Maria Garcia",
      userId: 2,
      action: "updated",
      target: "Backend Team settings",
      targetId: 2,
      targetType: "team",
      timestamp: "2025-04-20T14:22:45Z",
      ipAddress: "203.0.113.42",
    },
    {
      id: 3,
      user: "John Smith",
      userId: 3,
      action: "created",
      target: "New Project Dashboard",
      targetId: 5,
      targetType: "project",
      timestamp: "2025-04-20T11:05:18Z",
      ipAddress: "198.51.100.75",
    },
    {
      id: 4,
      user: "David Lee",
      userId: 5,
      action: "commented",
      target: "Task #1234",
      targetType: "task",
      timestamp: "2025-04-19T16:30:22Z",
      ipAddress: "172.16.254.1",
    },
    {
      id: 5,
      user: "Emily Wilson",
      userId: 6,
      action: "deleted",
      target: "Old Documentation",
      targetType: "document",
      timestamp: "2025-04-18T10:12:37Z",
      ipAddress: "192.168.1.105",
    },
  ])

  const handleRefresh = () => {
    // In a real app, this would fetch fresh data from the API
    toast.success("Data refreshed")
  }

  return {
    members,
    setMembers,
    teams,
    setTeams,
    projects,
    setProjects,
    roles,
    setRoles,
    permissions,
    setPermissions,
    activityLogs,
    setActivityLogs,
    handleRefresh
  }
}
